-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 16:46:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sas
-- -----------------------------------------------------
-- Base de datos del Sistema web de Análisis Socioemocional y de distribución de material educativo para la Universidad Politécnica del Estado de Morelos.
-- Proyecto de tesina de:
-- Jacinto Escobar Quezada      -  EQJO190657
-- Laura Itzel Martínez Chávez  - MCLO190493
DROP SCHEMA IF EXISTS `sas` ;

-- -----------------------------------------------------
-- Schema sas
--
-- Base de datos del Sistema web de Análisis Socioemocional y de distribución de material educativo para la Universidad Politécnica del Estado de Morelos.
-- Proyecto de tesina de:
-- Jacinto Escobar Quezada      -  EQJO190657
-- Laura Itzel Martínez Chávez  - MCLO190493
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sas` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `sas` ;

-- -----------------------------------------------------
-- Table `sas`.`Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sas`.`Clase` ;

CREATE TABLE IF NOT EXISTS `sas`.`Clase` (
  `idClase` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria para la tabla clase.',
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el nombre de la clase.',
  `descripcion` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para la descripción de la clase.',
  `cuatrimestre` INT NOT NULL COMMENT 'Campo para el cuatrimestre en que se imparte la clase.',
  `grupo` VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el grupo de la clase.',
  `carrera` ENUM('IBT', 'ITA', 'IIN', 'ITI', 'IET', 'IFI') CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para la carrera en la que se imparte la clase.',
  `codigo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el código de identificación e inscripción de la clase.',
  `idUsuario` INT NOT NULL COMMENT 'Llave foránea para identificar al usuario de tipo profesor que imparte la clase.',
  PRIMARY KEY (`idClase`),
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sas`.`Usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sas`.`Inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sas`.`Inscripcion` ;

CREATE TABLE IF NOT EXISTS `sas`.`Inscripcion` (
  `idInscripcion` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria de la tabla inscripción',
  `estado` ENUM('activo', 'pendiente', 'baja') CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el estado de la inscripción de un alumno a una clase.',
  `idClase` INT NOT NULL COMMENT 'Llave foránea para identificar a la clase en la que esta la inscripción.',
  `idUsuario` INT NOT NULL COMMENT 'Llave foránea para identificar al usuario de tipo alumno que se inscribió a una clase.',
  PRIMARY KEY (`idInscripcion`),
  CONSTRAINT `idClase`
    FOREIGN KEY ()
    REFERENCES `sas`.`Clase` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY ()
    REFERENCES `sas`.`Usuario` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sas`.`Topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sas`.`Topico` ;

CREATE TABLE IF NOT EXISTS `sas`.`Topico` (
  `idTopico` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria de la tabla topico.',
  `titulo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el título del tópico.',
  `descripcion` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para la descripción del tópico.',
  `idUnidadAprendizaje` INT NOT NULL COMMENT 'Llave foránea para identificar a la unidad de aprendizaje dentro de la que se encuentra el tópico.',
  PRIMARY KEY (`idTopico`),
  INDEX `idUnidadAprendizaje_idx` (`idUnidadAprendizaje` ASC) VISIBLE,
  CONSTRAINT `idUnidadAprendizaje`
    FOREIGN KEY (`idUnidadAprendizaje`)
    REFERENCES `sas`.`UnidadAprendizaje` (`idUnidadAprendizaje`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sas`.`UnidadAprendizaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sas`.`UnidadAprendizaje` ;

CREATE TABLE IF NOT EXISTS `sas`.`UnidadAprendizaje` (
  `idUnidadAprendizaje` INT NOT NULL COMMENT 'Llave primaria de la tabla UnidadAprendizaje.',
  `titulo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el título de la unidad de aprendizaje.',
  `descripcion` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para la descripción de la unidad de aprendizaje.',
  `idClase` INT NOT NULL COMMENT 'Llave foránea para identificar a la clase dentro de la que se encuentra la unidad de aprendizaje.',
  PRIMARY KEY (`idUnidadAprendizaje`),
  INDEX `idClase_idx` (`idClase` ASC) VISIBLE,
  CONSTRAINT `idClase`
    FOREIGN KEY (`idClase`)
    REFERENCES `sas`.`Clase` (`idClase`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sas`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sas`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `sas`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria de la tabla usuario.',
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el nombre o nombres.',
  `paterno` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el apellido paterno.',
  `materno` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el apellido materno.',
  `correo` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el correo electrónico.',
  `usuario` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el usuario de acceso al sistema.',
  `contraseña` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para la contraseña de acceso al sistema.',
  `tipo` ENUM('administrador', 'profesor', 'alumno') CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL COMMENT 'Campo para el tipo de usuario.',
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `sas`;

DELIMITER $$

USE `sas`$$
DROP TRIGGER IF EXISTS `sas`.`Clase_BEFORE_INSERT` $$
USE `sas`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Clase_BEFORE_INSERT` BEFORE INSERT ON `Clase` FOR EACH ROW
BEGIN
	SET new.codigo = concat(
    LEFT(new.nombre, 3),
    new.cuatrimestre,
    new.grupo,
    new.carrera
	);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
